### ISSUE TITLE
Move cryptomining domains from tags in the Advertising category to a new top-level category

### ISSUE THREAD

**Issue by groovecoder** [mozilla-services/shavar-list-creation#64] opened 2019-01-15 23:11 UTC
See https://github.com/mozilla-services/shavar-prod-lists/pull/43#issuecomment-454565973. Still digging into the cause here.

**Comment by englehardt** [comment] 2019-01-22 22:06
We are consuming the tags as intended, but perhaps we should reconsider the use of `cryptominer` as a tag.

IMO the tags are meant to annotate domains on the list with additional context beyond their top-level category. Some examples:
* An advertisement company which fingerprints will be present in the top-level `Advertisement` category and will receive a `fingerprinting` tag
* An analytics company that fingerprints and runs cryptominers, but also respects the EFF's version of DNT will be present in the top-level `Analytics` category and will receive a `fingerprinting`, `cryptominer` and `dnt=eff` tag.

`base-track-digest256` pulls all domains from the top-level `Advertisement`, `Analytics`, `Social`, and `Disconnect` categories. The `Disconnect` category is re-mapped into one of the other three. We don't want to filter out all domains that have tags from this list; domains with the `fingerprinting` tag are still advertising trackers and should still be blocked by the vanilla tracking protection and cookie restrictions. Also note that some of our mobile products pull in each individual category. E.g., `analytics-track-digest256` only contains domains from the top-level analytics category, but contains all domains in that category unless they have a certain DNT tag.

@patjack do all of the domains on the cryptomining list meet the "Advertising" category's definition? If not, I think it makes sense to create a new top-level category for them. That will require us to update our list creation and test scripts, but it shouldn't be too much work.

**Comment by patjack** [comment] 2019-01-24 05:53
@englehardt you're right - we are currently using the "Advertising" top-level category for the cryptominers and it could be classified better. I think it does make sense to create new top-level categories for domains that don't fit in the current categories. Does adding `Cryptominer` and `Fingerprinter` as new top-level categories sound good to you? If so, I can add support for that on our side and follow up with an example of the list with the new categories. Thanks for looking into this!

**Comment by englehardt** [comment] 2019-01-30 17:42
Updating the title the reflect the fix we converged on.

**Comment by patjack** [comment] 2019-01-30 23:08
I just pushed the updated list w/the new category `Cryptomining`. You can take a look here: [https://github.com/disconnectme/disconnect-tracking-protection/blob/master/services.json#L9410](url)

I have a few more changes/housekeeping items and will finish those before I submit a PR but just wanted to share the list w/new category first.

**Comment by englehardt** [comment] 2019-01-31 00:59
Thanks! This format looks good to me. I think you can drop the `"cryptominer": "true"` tags from these, given that that information is now redundant with the top-level category.

**Comment by englehardt** [comment] 2019-02-26 17:32
Fixed in https://github.com/mozilla-services/shavar-prod-lists/pull/54

**Closed by englehardt** 2019-02-26 17:32 UTC
